### ISSUE TITLE
I am not being able to replace the default config values

### ISSUE THREAD

**Issue by harrydema** [JustinBeckwith/retry-axios#101] opened 2020-04-03 14:41 UTC
Although I set the retry number to 2, the raxConfig shows that the retry keeps at 3.

![image](https://user-images.githubusercontent.com/13423169/78372745-0bb74a00-75a0-11ea-94ec-35e3d9110b0f.png)

**Comment by sk-** [comment] 2020-08-19 17:58
Probably a duplicate of #90

**Comment by JustinBeckwith** [comment] 2020-10-23 19:39
Hey folks - I believe the latest release of axios fixed this issue 🎉  Let me know if you're still running into issues!

**Closed by JustinBeckwith** 2020-10-23 19:39 UTC
