### ISSUE TITLE
Retries issues

### ISSUE THREAD

**Issue by Arjunalapsapkota** [JustinBeckwith/retry-axios#104] opened 2020-04-20 19:31 UTC
By default , retry count is set to 3. But It's only trying two times.  Doesn't have any effect if I define it to be 3, 4 or 5. It only tries 2 times. Please fix this issue. Thanks

**Comment by khitrenovich** [comment] 2020-06-17 14:26
Possible duplicate of #68

**Comment by quangogster** [comment] 2020-06-30 23:56
downgrading worked for me.  thanks @khitrenovich !

**Comment by moltar** [comment] 2020-08-19 11:34
Seeing this too. The setting has no effect and only 2 attempts are tried.

**Comment by sk-** [comment] 2020-08-24 22:22
@moltar How did you set up the raxConfig? I'm asking because I identified issue #124, in which if you use a custom axios instance, then it won't work unless you also specify the `instance` field.

**Comment by Tinadim** [comment] 2021-02-19 13:46
I was having a similar problem using the following setup:

```
const instance = Axios.create();
instance.defaults.raxConfig = { ... };
instance.get(...)
```

Changing the values in raxConfig above was having no effect. When I saw this ticket, I noticed I was using axios 0.19 and updated it to axios 0.21, which solved the problem for me

**Comment by JustinBeckwith** [comment] 2021-08-14 21:52
So this is a little confusing :) One thing to look out for here, are that there are separate settings for `retry` and `noResponseRetries`.  The `retry` number will be used if you connect to the endpoint, and get a non-2xx response.  The `noResponseRetries` is specifically used in the case where the connection was never made, like `ETIMEDOUT` or  `ENOTFOUND` errors.  

To get it to use 3 retries every time (regardless of the reason it fails), this ought to work:

```js
const rax = require('retry-axios');
const axios = require('axios');

rax.attach();

async function main() {
  try {
    await axios({
      url: 'https://test.local',
      raxConfig: {
        retry: 3,
        noResponseRetries: 3,
        onRetryAttempt: err => {
          const cfg = rax.getConfig(err);
          console.log(`Retry attempt #${cfg.currentRetryAttempt}`);
        }
      },
    });
  } catch (err) {
    console.error(err);
  }
}
main();
```

Note, this is using:
- Node.js 14.17..3
- axios 0.21.1
- retry-axios 2.5.0

For anyone else that comes here - please make sure to post the exact code you're using :) Also, it would be helpful to include the versions of axios and retry-axios, as well as the error you're getting when the request fails.

**Closed by JustinBeckwith** 2021-08-14 21:52 UTC

**Comment by orgads** [comment] 2023-11-16 08:43
It works with the default axios, but doesn't work with axios instance (`axios.create()`). See https://github.com/JustinBeckwith/retry-axios/issues/68#issuecomment-1812630595
